//!
//! Mailchimp Types
//!

mod api_root;
mod authorized_apps;
mod automation_campaign;
mod automation_email_queue;
mod automation_subscriber;
mod campaign;
mod campaign_content;
mod campaign_feedback;
mod campaign_send_checklist;
mod contact;
mod conversation_messages;
mod conversations;
mod ecommerce;
mod empty;
mod industry_stats;
mod link;
mod list;
mod list_abuse_report;
mod list_activity;
mod list_batch_members;
mod list_clients;
mod list_growth_history;
mod list_interest_categories;
mod list_interests;
mod list_locations;
mod list_member_activity;
mod list_member_goals;
mod list_member_notes;
mod list_member_tags;
mod list_members;
mod list_merge_fields;
mod list_segment_members;
mod list_segment_options;
mod list_segments;
mod list_signup_forms;
mod list_webhooks;
mod ping;
mod report;
mod workflow_email;

pub use self::api_root::*;
pub use self::authorized_apps::{AuthorizedAppType, AuthorizedAppsType, CreatedAuthorizedAppType};
pub use self::automation_campaign::*;
pub use self::automation_email_queue::*;
pub use self::automation_subscriber::*;
pub use self::campaign::*;
pub use self::campaign_content::*;
pub use self::campaign_feedback::*;
pub use self::campaign_send_checklist::*;
pub use self::contact::ContactType;
pub use self::conversation_messages::*;
pub use self::conversations::*;
pub use self::ecommerce::*;
pub use self::empty::*;
pub use self::industry_stats::*;
pub use self::link::LinkType;
pub use self::list::*;
pub use self::list_abuse_report::*;
pub use self::list_activity::*;
pub use self::list_batch_members::*;
pub use self::list_clients::*;
pub use self::list_growth_history::*;
pub use self::list_interest_categories::*;
pub use self::list_interests::*;
pub use self::list_locations::*;
pub use self::list_member_activity::*;
pub use self::list_member_goals::*;
pub use self::list_member_notes::*;
pub use self::list_member_tags::*;
pub use self::list_members::*;
pub use self::list_merge_fields::*;
pub use self::list_segment_members::*;
pub use self::list_segment_options::*;
pub use self::list_segments::*;
pub use self::list_signup_forms::*;
pub use self::list_webhooks::*;
pub use self::ping::*;
pub use self::report::*;
pub use self::workflow_email::*;
